// Mocks generated by Mockito 5.4.0 from annotations
// in gojo/test/features/property/review/presentation/bloc/review_form_bloc_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:gojo/features/property/review/data/models/review.dart' as _i2;
import 'package:gojo/features/property/review/data/repository/review_repository.dart'
    as _i3;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeReview_0 extends _i1.SmartFake implements _i2.Review {
  _FakeReview_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [ReviewRepositoryAPI].
///
/// See the documentation for Mockito's code generation for more information.
class MockReviewRepositoryAPI extends _i1.Mock
    implements _i3.ReviewRepositoryAPI {
  MockReviewRepositoryAPI() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.Review> createReview({
    required _i2.Review? review,
    required int? propertyId,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #createReview,
          [],
          {
            #review: review,
            #propertyId: propertyId,
          },
        ),
        returnValue: _i4.Future<_i2.Review>.value(_FakeReview_0(
          this,
          Invocation.method(
            #createReview,
            [],
            {
              #review: review,
              #propertyId: propertyId,
            },
          ),
        )),
      ) as _i4.Future<_i2.Review>);
}
