// Mocks generated by Mockito 5.4.0 from annotations
// in gojo_landlord/test/features/auth/signin/presentation/bloc/signin_bloc_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:dartz/dartz.dart' as _i2;
import 'package:gojo_landlord/features/auth/signin/data_layer/repository/sign_in_repository.dart'
    as _i3;
import 'package:gojo_landlord/Gojo-Mobile-Shared/core/model/user.dart' as _i5;
import 'package:gojo_landlord/Gojo-Mobile-Shared/core/repository/user_repository.dart'
    as _i6;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeEither_0<L, R> extends _i1.SmartFake implements _i2.Either<L, R> {
  _FakeEither_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [SignInRepositoryAPI].
///
/// See the documentation for Mockito's code generation for more information.
class MockSignInRepositoryAPI extends _i1.Mock
    implements _i3.SignInRepositoryAPI {
  MockSignInRepositoryAPI() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.Either<_i5.User, Exception>> authenticate({
    required String? phoneNumber,
    required String? password,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #authenticate,
          [],
          {
            #phoneNumber: phoneNumber,
            #password: password,
          },
        ),
        returnValue: _i4.Future<_i2.Either<_i5.User, Exception>>.value(
            _FakeEither_0<_i5.User, Exception>(
          this,
          Invocation.method(
            #authenticate,
            [],
            {
              #phoneNumber: phoneNumber,
              #password: password,
            },
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.User, Exception>>);
  @override
  _i4.Future<_i2.Either<void, Exception>> forgotPassword({
    required String? phoneNumber,
    required String? newPassword,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #forgotPassword,
          [],
          {
            #phoneNumber: phoneNumber,
            #newPassword: newPassword,
          },
        ),
        returnValue: _i4.Future<_i2.Either<void, Exception>>.value(
            _FakeEither_0<void, Exception>(
          this,
          Invocation.method(
            #forgotPassword,
            [],
            {
              #phoneNumber: phoneNumber,
              #newPassword: newPassword,
            },
          ),
        )),
      ) as _i4.Future<_i2.Either<void, Exception>>);
}

/// A class which mocks [UserRepositoryAPI].
///
/// See the documentation for Mockito's code generation for more information.
class MockUserRepositoryAPI extends _i1.Mock implements _i6.UserRepositoryAPI {
  MockUserRepositoryAPI() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<void> persistUser(_i5.User? user) => (super.noSuchMethod(
        Invocation.method(
          #persistUser,
          [user],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);
  @override
  _i4.Future<_i5.User?> getUser() => (super.noSuchMethod(
        Invocation.method(
          #getUser,
          [],
        ),
        returnValue: _i4.Future<_i5.User?>.value(),
      ) as _i4.Future<_i5.User?>);
  @override
  _i4.Future<void> deleteUser() => (super.noSuchMethod(
        Invocation.method(
          #deleteUser,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);
}
