// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAnUIRg9TQPXafXCi2fsyWWFT0zsm1Qbwo',
    appId: '1:942459374670:web:9bc2b4124ac8fee143c71f',
    messagingSenderId: '942459374670',
    projectId: 'gojo-b7999',
    authDomain: 'gojo-b7999.firebaseapp.com',
    storageBucket: 'gojo-b7999.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDuJTNdT2JM4ZnntqkPE11nbdrNJ2uITOs',
    appId: '1:942459374670:android:fe5192b057ea1aa543c71f',
    messagingSenderId: '942459374670',
    projectId: 'gojo-b7999',
    storageBucket: 'gojo-b7999.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBlphGY-xEsBJh7p1rrFu5SVCIdBEtG3_g',
    appId: '1:942459374670:ios:62e11153f2a0901f43c71f',
    messagingSenderId: '942459374670',
    projectId: 'gojo-b7999',
    storageBucket: 'gojo-b7999.appspot.com',
    iosClientId: '942459374670-muti2mqleif2buir7ffbonvpm4km9m9r.apps.googleusercontent.com',
    iosBundleId: 'com.example.gojo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBlphGY-xEsBJh7p1rrFu5SVCIdBEtG3_g',
    appId: '1:942459374670:ios:62e11153f2a0901f43c71f',
    messagingSenderId: '942459374670',
    projectId: 'gojo-b7999',
    storageBucket: 'gojo-b7999.appspot.com',
    iosClientId: '942459374670-muti2mqleif2buir7ffbonvpm4km9m9r.apps.googleusercontent.com',
    iosBundleId: 'com.example.gojo',
  );
}
